spring:
  datasource:
    url: jdbc:h2:mem:simple_blog
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      pool-name: simpe-blog-pool
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30
      connection-timeout: 10000
      connection-test-query: select 1
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2